import type { Metadata } from "next";
import NavBar from "@/components/common/NavBar";
import React from "react";
import '../styles/globals.css'
import Footer from "@/components/common/Footer";
import getCurrentUser from "@/app/actions/getCurrentUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const currentUserData = await getCurrentUser();
    console.log("layout", currentUserData);
  return (
    <html lang="en">
      <body>

        <NavBar  />
            {children}
        <Footer />

      </body>
    </html>
  );
}
