'use client'
// import type { Metadata } from "next";
import NavBar from "@/components/common/NavBar";
import React from "react";
import '../styles/globals.css'
import Footer from "@/components/common/Footer";
import {SessionProvider, useSession} from "next-auth/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
      <SessionProvider>
        <NavBar />
            {children}
        <Footer />
      </SessionProvider>
      </body>
    </html>
  );
}
