import type {Metadata} from "next";
import NavBar from "@/components/common/NavBar";
import React from "react";
import "../styles/globals.css";
import Footer from "@/components/common/Footer";
import getCurrentUser from "@/app/actions/getCurrentUser";
import ReduxProvider from "@/provider/ReduxProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const currentUserData = await getCurrentUser();
    console.log("currentUserData:{}", currentUserData);

    return (
        <html lang="en">
            <body>
                <ReduxProvider>
                    <NavBar  />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
